import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/shared/Navbar";
import ReactQueryProvider from "@/Providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider> {/* Wrap your application */}
          <div className="flex flex-row gap-10">
            <div className="min-h-screen w-[20%] bg-[#1D2939]">
              <Navbar />
            </div>
            <div className="min-h-screen bg-[#E9ECEF] w-[80%] mt-10">
              {children}
            </div>
          </div>
        </ReactQueryProvider> {/* End of the wrapper */}
      </body>
    </html>
  );
}
