
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/shared/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row gap-10">
          <div className="min-h-screen w-[25%] bg-[#1D5D9B]">
            <Navbar />
          </div>
          <div className="min-h-screen w-[75%]">
          {children}
          </div>
        </div>
        </body>
    </html>
  );
}
